version: '3.3'

services:
  asterisk:
    image: andrius/asterisk:18-arm64
    container_name: asterisk_sip_server
    restart: unless-stopped
    environment:
      - ASTERISK_UID=1000
      - ASTERISK_GID=1000
    volumes:
      - ./asterisk-config:/etc/asterisk
      - ./asterisk-logs:/var/log/asterisk
      - ./asterisk-data:/var/lib/asterisk
      - ./asterisk-spool:/var/spool/asterisk
    ports:
      - "5060:5060/udp"  # SIP UDP
      - "5060:5060/tcp"  # SIP TCP
      - "10000-20000:10000-20000/udp"  # RTP ports
    networks:
      - sip_network
    command: ["/usr/sbin/asterisk", "-f"]

networks:
  sip_network:
    driver: bridge
